### ISSUE TITLE
skpm install fails

### ISSUE THREAD

**Issue by yourfavorite** [sketch-symbol-importer/sketch-symbol-importer#1]
Looks like versions is missing from wherever its supposed to live. I see a version property in the package.json and the plugin manifest, but neither have a versions. Though I'm not even sure if that's where versions needs to exist.

```
$ skpm install sketch-symbol-importer
[1/3] 🗄  Getting the plugin information...
[2/3] 🗂  Finding the plugin version...
error Error while installing the plugin
TypeError: Cannot read property 'versions' of undefined
    at /usr/local/lib/node_modules/skpm/lib/skpm-install.js:84:18
    at Array.map (native)
    at /usr/local/lib/node_modules/skpm/lib/skpm-install.js:83:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by drewloomer** [comment]
I couldn't get it to publish to skpm the other day because of some network issues, so that may be the issue. If you do `skpm search sketch-symbol-importer` does it even find the package? If not, we'll need to get it published properly.

**Comment by yourfavorite** [comment]
You're right. It didn't get published properly. search returns `error No plugins found for "sketch-symbol-importer"`
